apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
  labels:
    name: myapp
spec:
  containers:
  - name: kubia
    image: localhost:5000/kubia:latest
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8080
      protocol: TCP
